[package]
name = "orderbook"
version = "0.1.0"
build = "serde/serde/default"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
